### ISSUE TITLE
find_codes doesn't search geo codes

### ISSUE THREAD

**Issue by tarakc02** [tarakc02/getcdw#7]
`find_codes` does not search code tables for MSAs and other region definitions.

**Comment by datalover916** [comment]
I searched brainstorm_bot for "san diego" and it did not return the MSA.

**Comment by tarakc02** [comment]
Nice catch, though that problem appears in the brainstorm bot, you can trace it back to `getcdw::find_codes`. The main issue is that the metadata in the data warehouse keeps most code tables in one view called `d_tms_type_mv`, (which is utilized in `find_codes` and hence in `brainstorm_bot`), but inexplicably separates out "geo" codes (MSAs, campaign regions, etc) into a separate view. I've asked AIM about consolidating these to make the codes easier to find -- that would be my preferred solution. But if they can't/won't do that, I'll modify the `find_codes` query to include the other places codes are found.
